### ISSUE TITLE
OP_PUSHNUM_X

### ISSUE THREAD

**Issue by vostrnad** [thunderbiscuit/opcode-explained#4]
Some script decoders (e.g. the one used by [mempool.space](https://mempool.space/)) display opcodes 81-96 as `OP_PUSHNUM_1`-`OP_PUSHNUM_16` instead of `OP_1`-`OP_16`, so these should probably be included as alternative names.

**Comment by thunderbiscuit** [comment]
Thank you for the tip! I didn't notice the alternative names but I should have, since I've been mostly looking at bitcoin core and rust bitcoin (rust bitcoin uses the `OP_PUSHNUM_X` names).
